version: '3.8'

services:
  todo:
    image: allenaira/todolist:latest
    container_name: todo
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: sql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: to_do_list_db
    networks:
      - net
    restart: always
    depends_on:
      - mysql 
  mysql:
    image: mysql
    container_name: sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    networks:
      - net
    volumes:
      - vol:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql  
    restart: always  
        
volumes:
    vol:

networks:
    net:


